export enum MutationKeys {
  CLAIM_NFT_BENEFIT = 'claim-nft-benefit',
  UPDATE_CLAIM_STATUS = 'update-claim-status',
  CREATE_BENEFIT = 'create-benefit',
  CREATE_BENEFIT_CATEGORY = 'create-benefit-category',
  UPDATE_NFT = 'update-nft',
  CREATE_NFT = 'create-nft',
  CREATE_CAMPAIGN = 'create-campaign',
  UPDATE_CAMPAIGN = 'update-campaign',
  BATCH_CREATE_NFTS = 'batch-create-nfts',
  CREATE_NFT_COLLECTION = 'create-nft-collection',
  CONFIRM_NFT_COLLECTION = 'confirm-nft-collection',
  UPDATE_NFT_COLLECTION = 'update-nft-collection',
  SEND_NFT = 'send-nft',
}
