import { UserHeader } from '@mlem-user/modules/user-header';
import { cn } from '@mlem-user/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <UserHeader />
        <div className="max-w-screen-xl mx-auto bg-white text-gray-900 antialiased">
          {children}
        </div>
      </body>
    </html>
  );
}
