version: '3.9'

services:
  ui:
    image: blhl1210/mlem-ui:latest
    container_name: "mlem-ui"
    env_file:
      - ./.env
    environment:
        - PORT=3000
        - NEXT_PUBLIC_API_URL=https://api.melem.io/v1
    restart: on-failure
    ports:
      - 8080:8080
