name: build

on:
  push:
    branches:
      - develop
      - ci/deploy-docker
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: blhl1210/mlem-ui:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Re-run docker compose
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo docker pull blhl1210/mlem-ui:latest
          cd /home/ubuntu/mlem-dashboard && sudo docker compose -f "docker-compose.yml" up -d --build
